### ISSUE TITLE
In Avro plugin, variable extraction should be flatMap except for the last component in the path

### ISSUE THREAD

**Issue by deaktator** [eHarmony/aloha#150]
### Feature Specifcation
```json
{ "name": "ids", "spec": "${x.y.ids} map ind" }
```

### Avro Data
```
record Y   { union { null, array<string> } ids = null; }
record X   { union { null, Y             } y   = null; }
record Msg { union { null, X             } x   = null; }
```

## Desire 
Produce an `Iterable[(String, Double)]` given the feature specification and Avro definitions.

## Problem
The following improper (*pretty-printed*) code is generated:

### Improperly generated code

```scala
{
import com.eharmony.aloha.feature.BasicFunctions._
import scala.math._
identity[GenAggFunc[Msg, Iterable[(String, Double)]]](
  GenFunc.f1(
    GeneratedAccessor(
      "x.y.ids",
      (_0: Msg) => {
        import scala.collection.JavaConversions.asScalaBuffer
        Option(_0.get("x")).asInstanceOf[Option[GenericRecord]].flatMap(_1 =>
          Option(_1.get("y")).asInstanceOf[Option[GenericRecord]].map(_2 =>   // <== !!!
            Option(_2.get("ids")).asInstanceOf[Option[java.util.List[CharSequence]]].map(
              _.toSeq.map(_.toString)))).getOrElse(Nil)
      },
      None
    )
  )(
    "${x.y.ids} map ind",
    (_x__y__ids) => {
     _x__y__ids map ind
    }
  )
)
}
```

The problem lies in the generated code for the `GeneratedAccessor`.  What this really should like is something like the following:

### Expected results (in *for comprehension* style)
```scala
import org.apache.avro.generic.GenericRecord
import com.zefr.avro.training.TrainingRelevancy

val f = (_0: Msg) => {
  import scala.collection.JavaConversions.asScalaBuffer
  (
  for {
    _1 <- Option(_0.get("x")).asInstanceOf[Option[GenericRecord]]
    _2 <- Option(_1.get("y")).asInstanceOf[Option[GenericRecord]]
    _3 <- Option(_2.get("ids")).asInstanceOf[Option[java.util.List[CharSequence]]]
  } yield _3.toSeq.map(_.toString)
  ) getOrElse Nil
}
```

So the problem lies in the improperly generated code emitting a `map` when a `flatMap` should be emitted.

```scala
val g = (_0: Msg) => {
  import scala.collection.JavaConversions.asScalaBuffer
  Option(_0.get("x"))
    .asInstanceOf[Option[GenericRecord]]
    .flatMap(_1 =>
      Option(_1.get("y"))
        .asInstanceOf[Option[GenericRecord]]
        .flatMap(_2 =>          // <== Problem line: Needs to be flatMap
          Option(_2.get("ids"))
            .asInstanceOf[Option[java.util.List[CharSequence]]]
            .map(_.toSeq.map(_.toString))
        )
    ).getOrElse(Nil)
}
```

This is going to be the case for all instances, regardless how long the path to get a variable is.  

**TODO**: Figure out if there are any nuances here or just alway emit `flatMap`.

**Comment by bahman-engheta-zefr** [comment]
@deaktator, 

Given the general [implementation](https://github.com/eHarmony/aloha/blob/89e361ba8cf0d64c0aff6271989ea7e4fbc8f901/aloha-core/src/main/scala/com/eharmony/aloha/feature/Indicator.scala#L7) of `trait Indicator`, which can accept an `Iterable[String]`, would `ind(${x.y.ids})` also work (and generate the same result)? 

@bahman-engheta-zefr

**Comment by deaktator** [comment]
@bahman-engheta-zefr You're right.  `ind(${x.y.ids})` should produce the same result as `${x.y.ids} map ind`.  They should be about the same in terms of efficiency as far as I can tell.

**Comment by deaktator** [comment]
This problem likely due to the fact that Avro code is a generalization of the original Protocol Buffer-based semantics but Avro supports additional language features not in Protocol Buffers.  In Protocol Buffers (at least *2.4.1*), there are *required*, *optional*, and *repeated* fields.  In Avro, since it supports generalized unions, fields representing sequences can be optional by virtue of definitions like:

```
union { null, array<string> } ids = null;
```

To get around this, I think a change to [line 68](https://github.com/eHarmony/aloha/blob/master/aloha-core/src/main/scala/com/eharmony/aloha/semantics/compiled/plugin/schemabased/SchemaBasedSemanticsPlugin.scala#L68) of `SchemaBasedSemanticsPlugin` is what's required.

```scala
val rep = repeated map { 
  r => cg.containerCodeGen(br, 
                           r, 
                           bfms.size + bms.size + 1, 
                           if (mapList) MAP else NONE) // <== Need FLAT_MAP case, I think.
}
```

**Comment by deaktator** [comment]
I don't think the above is the issue.  It may still be, but I need to investigate further.  I am pretty sure this isn't related to the avro code generators.  I think it's an issue in `aloha-core`.  I need to add some more unit tests for the following cases:

```scala
semantics.createFunction("ind(${opt_c1.opt_c2.opt_rep_str_3})")
semantics.createFunction("ind(${req_c1.opt_c2.opt_rep_str_3})")
semantics.createFunction("ind(${opt_c1.req_c2.opt_rep_str_3})")
semantics.createFunction("ind(${req_c1.req_c2.opt_rep_str_3})")

semantics.createFunction("ind(${opt_c1.opt_c2.rep_str_3})")
semantics.createFunction("ind(${req_c1.opt_c2.rep_str_3})")
semantics.createFunction("ind(${opt_c1.req_c2.rep_str_3})")
semantics.createFunction("ind(${req_c1.req_c2.rep_str_3})")

// These need to be added to the Avro testing schema.
semantics.createFunction("ind(${opt_c1.opt_c2.opt_rep_int_3})")
semantics.createFunction("ind(${req_c1.opt_c2.opt_rep_int_3})")
semantics.createFunction("ind(${opt_c1.req_c2.opt_rep_int_3})")
semantics.createFunction("ind(${req_c1.req_c2.opt_rep_int_3})")

semantics.createFunction("ind(${opt_c1.opt_c2.rep_int_3})")
semantics.createFunction("ind(${req_c1.opt_c2.rep_int_3})")
semantics.createFunction("ind(${opt_c1.req_c2.rep_int_3})")
semantics.createFunction("ind(${req_c1.req_c2.rep_int_3})")
```

**Comment by ryan-deak-zefr** [comment]
This can be fixed by modifying the mapping partition in `SchemaBasedSemanticsPlugin`.  Originally, when written for protocol buffers (whose repeated fields are not also optional), the `determineMappingPartition` function could **map** the last chain of `(R*O)` fields (R = *required*, O = *optional*).  Because in Avro any field can be nullable by unioning with the *null* type, we need to handle this.  To do so, we

1. Determine if there's an optional repeated field.
1. If so, **flat map** the last chain prior to the optional repeated field.
1. Otherwise, **map** as was previously done.
