### ISSUE TITLE
Aloha VW JNI model is no longer serializable

### ISSUE THREAD

**Issue by jmorra** [eHarmony/aloha#25]
I'm trying to serialize the Aloha VW JNI model after updating the to latest code and I'm seeing the following exception:

java.io.NotSerializableException: org.apache.commons.vfs2.provider.local.LocalFile

This is being triggered by a call to SparkContext.broadcast of an Aloha VW JNI model.  After looking at the code the culprit appears to be the vwModel object.  Can this please be changed so that it is serializable again.

**Comment by deaktator** [comment]
Yup.  Can you skype me
