### ISSUE TITLE
Automatically add latest maven release to site

### ISSUE THREAD

**Issue by deaktator** [eHarmony/aloha#37]
Use an async ajax request to maven central to automatically pull latest Aloha release.

**Comment by jmorra** [comment]
This may seem a little late, but is this really necessary.  Is there ever a case where the current snapshot version is not x.x.x -1?

**Comment by deaktator** [comment]
Yes.  deleted versions, etc.  You never know.  I think it's a bad
assumption.  Plus, if using semantic versioning, you might bump one of the
first two version numbers.
