### ISSUE TITLE
Model Serialization

### ISSUE THREAD

**Issue by jmorra** [eHarmony/aloha#66]
Some types of models are not serializable and therefore cannot be used with Spark.  The one I see is Exception in thread "main" java.io.NotSerializableException: com.eharmony.aloha.util.rand.HashedCategoricalDistribution.

For this ticket please go through all model types and ensure they are all serializable.

**Comment by deaktator** [comment]
Good catch. To be fair that's not in the contract.  Here's the plan. Use reflections in aloha-cli (which depends on all other modules) to ensure that each class extending model has a corresponding unit test with a testSerialization test.  This will ensure we're not missing anything.

I think we need to discuss the serialization mechanism if we are going to guarantee serializability for all models.

Should the model trait extend serializable? Or should there be a notion of a serializer that can be brought into the implicit scope? This second strategy is much more in line with the scala ecosystem.  Additionally, we could make use of some of Heather Miller's work to generate these serializers automatically.  Maybe the right thing is to do both.  Or maybe the right thing is to use Twitter bijection.  Let's talk about this more.
