### ISSUE TITLE
more descriptive cli error messages

### ISSUE THREAD

**Issue by larsena3** [eHarmony/aloha#77]
I was working with Aloha and receiving the below error every now and then after altering the spec file. A more descriptive error message would be helpful. 

" Couldn't create writer for dataset type csv. Error: No applicable producer found.  Given Producer"

**Comment by deaktator** [comment]
@larsena3 Fixing today (2016-01-19).

**Comment by deaktator** [comment]
Two changes.  

The first is better names for RowCreatorProducers.  This is introduced in a trait called `com.eharmony.aloha.dataset.RowCreatorProducerName` that gives more standardized names and handles inner class names better.

The second is including the error messages that were originally only previously included in the _INFO_ logs.

The message now looks like the following: 

```
Couldn't create writer for dataset type csv. Error: No applicable producer found.  Given CsvRowCreator.Producer.
Error Msgs: 1 failure occurred while attempting to produce spec:
    0)  CsvRowCreator.Producer: Object is missing required member 'imports'
        spray.json.package$.deserializationError(package.scala:23)
        spray.json.ProductFormats$class.fromField(ProductFormats.scala:61)
        com.eharmony.aloha.dataset.csv.json.CsvJson$.fromField(csvJson.scala:34)
        spray.json.ProductFormatsInstances$$anon$5.read(ProductFormatsInstances.scala:130)
        spray.json.ProductFormatsInstances$$anon$5.read(ProductFormatsInstances.scala:118)
        ...
```

**Comment by deaktator** [comment]
Please continue conversation on PR #78.
