### ISSUE TITLE
Make auditor output type

### ISSUE THREAD

**Issue by jmorra** [eHarmony/aloha#8]
Remove the notion of a ScoreProto and replace that with a recursive data type that allows representation of all the subscores.

**Comment by deaktator** [comment]
Possible implementation.  Needs to be callable from java but only needs to be able to be implemented from scala.  Most likely need to add F-bounded polymorphic type parameter.  See scala types of types,  [f-bounded type](http://ktoso.github.io/scala-types-of-types/#f-bounded-type).  

``` scala
/**
 *
 * @tparam K
 * @tparam R
 * @tparam O
 */
trait Aud[K, -R, -O] {
  type Audited[_]
  def leaf(k: K, r: R): O
  def node[C](k: K, r: R, Iterable[Audited[C]]): O
}
```

``` scala
/**
 * An auditor that doesn't audit but just passes through scores.
 * @tparam K
 * @tparam R
 * @tparam O
 */
class NoAud[K, V] extends Aud[K, V, V] {
  type Audited[A] = A
  def leaf(k: K, v: V): V = v
  def node[C](k: K, v: V, Iterable[Audited[C]]): V = v
}
```

**Comment by deaktator** [comment]
For a full writeup and solution, see https://deaktator.github.io/2015/08/01/recursive-auditing/

Then we need to modify the factory code and all of the model code.  This should really be a 3.0 branch.

**Comment by deaktator** [comment]
Should add basic Java unit tests before doing much more to make sure this works OK.

**Comment by deaktator** [comment]
I think the factory will need to be created via a factory method.  This way, Java invocation can work using type inference.  Something like:
 
```scala
/**
  * @tparam B MorphableAuditor input type.  This is the same as the ''natural output 
  *           type'' of the model being produced.  For instance, in a regression model, 
  *           the natural output type would be a real-valued type such as `Float` or 
  *           `Double`.
  * @tparam Y MorphableAuditor output type.
  * @tparam MA MorphableAuditor type.
  */
trait Factory[B, Y, MA <: MorphableAuditor[ModelId, B, Y, MA]] {
  /** 
    * Main model creation method.
    * 
    * Semantics is injected here so that submodels with different domains can be created.
    * 
    * '''NOTE''': the model output type, `Y`, is the same as the [[MorphableAuditor]]
    * output type.
    */
  def createModel[A](sem: Semantics[A], src: SrcType): Either[String, Model[A, Y]]

  // This probably shouldn't be in the base trait.  
  // Just here to show a possible function signature.
  protected[this] def createSubModel[A, C: RefInfo](sem: Semantics[A], src: SrcType): 
    Either[String, Model[A, MA#AuditOutput[C]]]
}

object Factory {
  /** Standard method that will suffice for most situations. */
  def apply[B, Y, MA <: MorphableAuditor[ModelId, B, Y, MA]](aud: M): Factory[B, Y, MA]
  
  /** Allows the user to add model implementations defined outside Aloha. */
  def apply[B, Y, MA <: MorphableAuditor[ModelId, B, Y, MA]](
    aud: M, 
    parsers: Seq[ModelParser]): Factory[B, Y, MA]
}
```

Then Java users can do something like: 

```java
final NoAudit<ModelId, Double> aud = new NoAudit<ModelId, Double>();

// User can define the value on the RHS and use an IDE to automatically fill in 
// the type on the LHS.
final Factory<Double, Option<Double>, NoAudit<ModelId, Double>> factory = 
  Factory.apply(aud);

// OR ...

final Semantics<A> sem = ...
final SrcType src = ...

// Returns Model<A, Option<Double>>
Factory.apply(aud)            // Get factory
       .createModel(sem, src) // Get either error string or model
       .right().get();        // Force getting model, fail on a failure
```

Then models created by the factory will return `Option<Double>`, which is `Factory`'s second type parameter.

**Comment by deaktator** [comment]
I just committed code that unifies the way factories will be created in Java and Scala.  I just decided I don't like this because there are fundamental differences in the way errors are should be treated in Java and Scala.  In Java, errors should be *thrown* as `Exception`s and in Scala, errors should be returned as typed objects.  When returning an `Either` to Java, it results in a **raw** `RightProjection` (with no type parameters).  This is a Scala bug.  The problem manifests itself in the fact that the `RightProjection` must be cast to one with type parameters.  **This is unacceptable!**  Therefore, I'll work on Scala and Java specific factories that solve these issues.  The Scala Factories could be called from Java but the Java ones will be simpler to use.

**Comment by deaktator** [comment]
# Notes (12/12/16)

## ModelFactory implementations will have zero-arg constructors

Previously, I decided to have static factory methods to create factories themselves.  I still think this may be desirable to control the creation of factories, but for now I'm going to concentrate on a Scala factory class with a zero-arg constructor (and possibly other constructors) and a separate Java facade that wraps a standard Scala factory class.

## Submodel's Auditor's AuditOutput is same as containing model's Auditor's

While initially surprising, it makes sense in retrospect that submodels are somewhat difficult to encode.  Each `AuditedModel[A, N, B]` has an `Auditor[ModelIdentity, N, B]`.  What's important here is how the signatures of  the `success` and `failure` methods in `Auditor` relate to submodel output values.  Both methods are parametrized by the submodel's natural output type `S`. This is the same type as the submodel's Auditor input type.  Looking at `subValues` is really important.  It shows that the submodels' output types are related to the containing model's `Auditor`'s `AuditOutput` type constructor.  For instance the signature

```scala
// Outer model's auditor
success[S](..., subValues: Seq[AuditOutput[S]], ...)
//                             ^^^^^^^^^^^^^^
//                         Submodels' output type
```

shows `outerModel.innerModel.auditor.AuditOutput` is a subtype of  `outerModel.auditor.AuditOutput`.  To make it easier to encode this relationship, we can use two argument lists and path dependent types in a model's factory method.  The submodel must be in the second argument list and it's output type can be related back to the outer model's Auditor's AuditOutput type.   Unfortunately, Scala doesn't allow this two argument list trick to be done in constructors so we have to use the companion object to create the models. Presumably, that's no big deal and worth the generalizability.  No one who's using Aloha in prod should really be instantiating models directly anyway other than for the simplest cases like constant models.

For example, 


```scala
abstract class HierarchicalConstantModel[-A, SN, N, +B](
    override val modelId: ModelIdentity, 
    constant: N
    )  extends AuditedModel[A, N, B] {

  val auditor: Auditor[ModelIdentity, N, B]  // <-- val b/c stable identifier needed
  def sub: Model[A, auditor.AuditOutput[SN]] // <-- Look at this type!
  def apply(a: A): B = auditor.success(modelId, constant, subValues = Seq(sub(a)))
}

object HierarchicalConstantModel {
  def apply[A, SN, N, B](mId: ModelIdentity, 
                         v: N, 
                         aud: Auditor[ModelIdentity, N, B])
                        (s: AuditedModel[A, SN, aud.AuditOutput[SN]]) = {
    new HierarchicalConstantModel[A, SN, N, B](mId, v) {
      // val b/c stable identifier needed.
      // aud.type necessary b/c s's output type is related to a 
      // path-dependent type based on aud.
      val auditor: aud.type = aud

      // Notice the type depends on the outer model's Auditor.
      val sub: AuditedModel[A, SN, auditor.AuditOutput[SN]] = s
    }
  }
}
```
