### ISSUE TITLE
Aloha H2O model doesn't support options

### ISSUE THREAD

**Issue by jmorra** [eHarmony/aloha#98]
We need to support the ability to have optional types in the CSV producers.  This translates into H2O models that support options.

**Comment by deaktator** [comment]
Currently, Aloha supports the CSV dataset pipeline as an Applicative Functor (_of_ `Option`s).  For instance, a specification author can create a function that takes two variables `a` and `b` of types `A` and `B`, `(a: A, b: B) => C` and the framework takes care of dealing with missing data when creating the CSV.  This works via something like: 

``` scala
// Possible implementation in scalaz
val f: (A, B) => C = ???
val ao: Option[A] = ???
val bo: Option[B] = ???
Applicative[Option].ap2(ao, bo)(f)
```

The goal of this is to make the the pipeline monadic. The big change is the shape of `f`:

``` scala
val f: (A, B) => Option[C] = ???
```

Then the calling code looks like:

``` scala
val ao: Option[A] = ???
val bo: Option[B] = ???
for {
  a <- ao
  b <- bo
  c <- f(a, b)
} yield c
```

**Comment by deaktator** [comment]
This change will be for CSV data in `com.eharmony.aloha.dataset.csv` in _aloha-core_ and `com.eharmony.aloha.models.h2o` in _aloha-h2o_.
